# Railway Deployment Configuration for Discord Bot
# This file tells Railway how to deploy the bot

version: 1

build:
  commands:
    - cd bot && npm install
    - cd bot && npm run build

deploy:
  startCommand: cd bot && npm start
  
env:
  NODE_ENV: production
