name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
      
    - name: Install web dependencies
      run: cd web && npm install
      
    - name: Install bot dependencies
      run: cd bot && npm install
      
    - name: Type check web
      run: cd web && npm run type-check
      
    - name: Type check bot
      run: cd bot && npx tsc --noEmit
      
    - name: Lint web
      run: cd web && npm run lint
      
    - name: Build web
      run: cd web && npm run build
      
    - name: Build bot
      run: cd bot && npm run build

  deploy-web:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./web
